# Generated by Django 4.1.3 on 2023-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fashionsavelist_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionsavelist',
            name='price',
        ),
    ]
