# Generated by Django 4.1.3 on 2023-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=3),
        ),
    ]
