# Generated by Django 4.1.3 on 2023-02-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_review_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsavelist',
            name='using_item',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
