# Generated by Django 4.1.3 on 2023-02-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fashionsavelist_using_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.TextField(default='Free', max_length=4),
        ),
    ]
