# Generated by Django 4.1.3 on 2023-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_item_bought_review_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsavelist',
            name='sex',
            field=models.CharField(default='Free', max_length=5),
        ),
    ]
