# Generated by Django 4.1.3 on 2023-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fashionsavelist_clothing_fashionsavelist_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionsavelist',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
