# Generated by Django 4.1.3 on 2023-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_fashionsavelist_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsavelist',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
