# Generated by Django 4.1.3 on 2023-02-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_fashionitemlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashionitemlist',
            old_name='fashion_item',
            new_name='fashion_id',
        ),
    ]
