# Generated by Django 4.1.3 on 2023-02-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_fashionitemlist_fashion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitemlist',
            name='FSL',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist'),
        ),
    ]
