# Generated by Django 4.1.3 on 2023-03-01 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_alter_fashionitemlist_using_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeForItem',
            new_name='LikeForPost',
        ),
    ]
