# Generated by Django 4.1.3 on 2023-03-02 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0037_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_item', models.CharField(max_length=200, verbose_name='お気に入りアイテム')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ファッション使用アイテム一覧',
                'verbose_name_plural': 'ファッション使用アイテム一覧',
            },
        ),
    ]
