# Generated by Django 4.1.3 on 2023-03-02 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_favoriteitemlist_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteitemlist',
            options={'verbose_name': 'お気に入りアイテム一覧', 'verbose_name_plural': 'お気に入りアイテム一覧'},
        ),
        migrations.AddField(
            model_name='favoriteitemlist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
