# Generated by Django 4.1.3 on 2023-02-18 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fashionsavelist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
