# Generated by Django 4.1.3 on 2023-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_id',
            field=models.IntegerField(default=1),
        ),
    ]
