# Generated by Django 4.1.3 on 2023-02-20 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_item_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
