# Generated by Django 4.1.3 on 2023-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_review_content_id_alter_review_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionsavelist',
            options={'verbose_name': 'ファッション一覧', 'verbose_name_plural': 'ファッション一覧'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品一覧', 'verbose_name_plural': '商品一覧'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文履歴', 'verbose_name_plural': '注文履歴'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '注文一覧', 'verbose_name_plural': '注文一覧'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支払一覧', 'verbose_name_plural': '支払一覧'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿一覧', 'verbose_name_plural': '投稿一覧'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'レビュー一覧', 'verbose_name_plural': 'レビュー一覧'},
        ),
        migrations.AddField(
            model_name='item',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
