# Generated by Django 4.1.3 on 2023-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_fashionsavelist_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bought',
        ),
        migrations.AddField(
            model_name='review',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
