# Generated by Django 4.1.3 on 2023-02-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fashionsavelist_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsavelist',
            name='clothing',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='fashionsavelist',
            name='season',
            field=models.CharField(default='オールシーズン', max_length=100),
        ),
        migrations.AlterField(
            model_name='fashionsavelist',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
