# Generated by Django 4.1.3 on 2023-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='None', max_length=10, verbose_name='色'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='値段'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(default='Free', max_length=5, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='固有ID'),
        ),
    ]
