# Generated by Django 4.1.3 on 2023-02-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using_item', models.CharField(max_length=20)),
                ('fashion_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist')),
            ],
            options={
                'verbose_name': 'ファッション使用アイテム一覧',
                'verbose_name_plural': 'ファッション使用アイテム一覧',
            },
        ),
    ]
