# Generated by Django 4.1.3 on 2023-02-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_fashion_item_fashionitemlist_fashion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitemlist',
            name='fashion_id',
        ),
        migrations.AddField(
            model_name='fashionitemlist',
            name='FSL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist'),
            preserve_default=False,
        ),
    ]
