# Generated by Django 4.1.3 on 2023-02-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_fashionitemlist_fsl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitemlist',
            name='FSL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fashionsavelist'),
        ),
    ]
