# Generated by Django 4.1.3 on 2023-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_fashionsavelist_using_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionsavelist',
            name='slug',
            field=models.IntegerField(),
        ),
    ]
