# Generated by Django 4.1.3 on 2023-03-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_favoriteitemlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitemlist',
            name='item',
        ),
    ]
