# Generated by Django 4.1.3 on 2023-03-05 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0044_alter_item_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('白', '白'), ('グレー', 'グレー'), ('黒', '黒'), ('ピンク', 'ピンク'), ('赤', '赤'), ('オレンジ', 'オレンジ'), ('ベージュ', 'ベージュ'), ('茶', '茶'), ('黄', '黄'), ('緑', '緑'), ('青', '青'), ('紫', '紫'), ('ネイビー', 'ネイビー'), ('カーキ', 'カーキ'), ('ゴールド', 'ゴールド'), ('アザー', 'アザー'), ('アイボリー', 'アイボリー'), ('オリーブ', 'オリーブ')], default='None', max_length=10, verbose_name='色'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(choices=[('自由', '自由'), ('男性', '男性'), ('女性', '女性')], default='自由', max_length=5, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
    ]
